// test/ownerDashboardServer.test.js
//
// M12-8C Package C — ownerDashboardServer loopback HTTP boundary (TDD RED→GREEN).
//
// The server is tested via its request HANDLER directly with injected service
// fakes + a fake req/res (no real socket, no fs, no git) so every boundary rule
// is asserted deterministically and purely:
//   - bearer required for /api/* (no/malformed/wrong → fixed 401, token never in body),
//   - bind 127.0.0.1 only + port 0|1024..65535, any other host/port rejected BEFORE listen,
//   - GET only (other methods → 405), unknown route → fixed 404,
//   - strict query bounds + closed categories + NO client-supplied runDir/workspaceRoot,
//   - injected errors → fixed safe code, NO raw text (and never token/path/exception),
//   - mandatory safe headers (no-store/nosniff/no-referrer/CSP) and NO CORS opt-in,
//   - happy path threads bounded client facts to the read-only service.

import { test } from "node:test";
import assert from "node:assert/strict";
import { join } from "node:path";

import { createOwnerDashboardServer } from "../src/ownerDashboardServer.js";

// ===== Fake req/res + drive helper (pure, in-memory) =====

function drive(handler, { method = "GET", url = "/", headers = {} } = {}) {
  const req = { method, url, headers: { ...headers } };
  const state = { statusCode: 200, headers: {}, body: "", ended: false };
  const res = {
    setHeader(k, v) { state.headers[String(k).toLowerCase()] = v; },
    writeHead(status) { state.statusCode = status; },
    write(c) { state.body += typeof c === "string" ? c : Buffer.from(c).toString("utf8"); },
    end(c) { if (c !== undefined) this.write(c); state.ended = true; },
    getHeader(k) { return state.headers[String(k).toLowerCase()]; },
  };
  const p = handler(req, res);
  return Promise.resolve(p).then(() => ({
    status: state.statusCode, headers: state.headers, body: state.body, ended: state.ended,
  }));
}
const jsonOf = (r) => JSON.parse(r.body);

// Build a server with deterministic service fakes. The token is generated by
// the factory (exercising the real bearer path); tests read it back via .token.
function makeServer({ runsFn, activityFn, host, port, randomBytesFn } = {}) {
  const runs = runsFn ?? (async () => ({ runs: [], returnedCount: 0, matchedCount: 0, truncated: false }));
  const activity = activityFn ?? (async () => ({
    runId: "run_x", available: true, unavailableReason: null,
    activity: { entries: [], total: 0, counts: {}, nextCursor: null },
    liveness: { ownerHeartbeat: "n/a", secondsSinceHeartbeat: null },
  }));
  return createOwnerDashboardServer({
    runDir: "/server/owned/runs", workspaceRoot: "/server/owned/ws",
    knownAgentIds: ["coder_low"], env: {},
    ...(host !== undefined ? { host } : {}),
    ...(port !== undefined ? { port } : {}),
    ...(randomBytesFn !== undefined ? { randomBytesFn } : {}),
    getOwnerRunsFn: runs, getOwnerActivityFn: activity,
    nowFn: () => 1_000_000,
  });
}

// Assert the common safe headers are present and CORS is NOT opted into.
function assertSafeHeaders(r) {
  assert.equal(r.headers["cache-control"], "no-store");
  assert.equal(r.headers["x-content-type-options"], "nosniff");
  assert.equal(r.headers["referrer-policy"], "no-referrer");
  assert.ok(r.headers["content-security-policy"], "CSP set");
  assert.ok(!("access-control-allow-origin" in r.headers), "no CORS opt-in (no ACAO)");
  assert.equal(r.headers["content-type"], "application/json; charset=utf-8");
}

// =====================================================================
// BEARER — required for every /api/*; no/malformed/wrong → fixed 401
// =====================================================================
test("BEARER: /api/runs with no Authorization → 401 unauthorized, token never in body", async () => {
  const s = makeServer();
  const r = await drive(s.handler, { url: "/api/runs" });
  assert.equal(r.status, 401);
  assert.deepEqual(jsonOf(r), { error: "unauthorized" });
  assertSafeHeaders(r);
  assert.ok(!r.body.includes(s.token), "token never in body");
  assert.ok(!JSON.stringify(r.headers).includes(s.token), "token never in headers");
});

test("BEARER: malformed Authorization (not 'Bearer ...') → 401", async () => {
  const s = makeServer();
  for (const h of [
    { authorization: s.token }, // missing scheme
    { authorization: "Basic " + s.token }, // wrong scheme
    { authorization: "Bearer" }, // no value
    { authorization: "Bearer  " }, // empty value
    { authorization: "bearer " + s.token }, // lowercase scheme is NOT accepted (strict)
  ]) {
    const r = await drive(s.handler, { url: "/api/runs", headers: h });
    assert.equal(r.status, 401, `401 for ${JSON.stringify(h)}`);
    assert.deepEqual(jsonOf(r), { error: "unauthorized" });
  }
});

test("BEARER: wrong token → 401 (timing-safe compare, token never in body)", async () => {
  const s = makeServer();
  const r = await drive(s.handler, { url: "/api/runs", headers: { authorization: "Bearer " + "0".repeat(s.token.length) } });
  assert.equal(r.status, 401);
  assert.deepEqual(jsonOf(r), { error: "unauthorized" });
  assert.ok(!r.body.includes(s.token));
});

test("BEARER: correct token → 200; /health needs no token", async () => {
  const s = makeServer();
  const ok = await drive(s.handler, { url: "/api/runs", headers: { authorization: "Bearer " + s.token } });
  assert.equal(ok.status, 200);
  const health = await drive(s.handler, { url: "/health" });
  assert.equal(health.status, 200);
  assert.deepEqual(jsonOf(health), { status: "ok" });
});

// =====================================================================
// HOST / PORT — reject non-loopback host + invalid port BEFORE listen
// =====================================================================
test("HOST: only 127.0.0.1 accepted; any other host rejected before listen", () => {
  for (const host of ["0.0.0.0", "::1", "localhost", "192.168.1.1", "", "127.0.0.2"]) {
    assert.throws(
      () => makeServer({ host }),
      /host|loopback|127/i,
      `rejects host ${JSON.stringify(host)} before listen`,
    );
  }
  // Valid default + explicit loopback do not throw.
  assert.doesNotThrow(() => makeServer({}));
  assert.doesNotThrow(() => makeServer({ host: "127.0.0.1" }));
});

test("PORT: 0 or 1024..65535 accepted; anything else rejected before listen", () => {
  for (const port of [80, 443, 1023, 65536, 70000, -1, 1.5, "8080", NaN, Infinity, null]) {
    assert.throws(
      () => makeServer({ port }),
      /port/i,
      `rejects port ${JSON.stringify(port)} before listen`,
    );
  }
  for (const port of [0, 1024, 8080, 65535]) {
    assert.doesNotThrow(() => makeServer({ port }), `accepts port ${port}`);
  }
  // undefined port → default (0), no throw.
  assert.doesNotThrow(() => makeServer({}));
});

// =====================================================================
// METHOD — GET only; everything else → 405 with Allow: GET
// =====================================================================
test("METHOD: non-GET → 405 with Allow: GET (incl. OPTIONS = no CORS)", async () => {
  const s = makeServer();
  for (const method of ["POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"]) {
    const r = await drive(s.handler, { method, url: "/api/runs", headers: { authorization: "Bearer " + s.token } });
    assert.equal(r.status, 405, `${method} → 405`);
    assert.equal(r.headers.allow, "GET");
    assert.deepEqual(jsonOf(r), { error: "method_not_allowed" });
    assertSafeHeaders(r);
    // OPTIONS must NOT opt into CORS.
    assert.ok(!("access-control-allow-origin" in r.headers));
  }
});

// =====================================================================
// ROUTE — unknown route → fixed 404 (GET)
// =====================================================================
test("ROUTE: unknown GET route → fixed 404", async () => {
  const s = makeServer();
  for (const url of ["/", "/unknown", "/api/foo", "/api/", "/api/runs/extra"]) {
    const r = await drive(s.handler, { url });
    assert.equal(r.status, 404, `${url} → 404`);
    assert.deepEqual(jsonOf(r), { error: "not_found" });
    assertSafeHeaders(r);
  }
});

// =====================================================================
// QUERY — strict bounds, closed categories, NO client runDir/workspaceRoot
// =====================================================================
test("QUERY /api/activity: missing/invalid runId → 400", async () => {
  const s = makeServer();
  const auth = { authorization: "Bearer " + s.token };
  for (const url of ["/api/activity", "/api/activity?runId=", "/api/activity?runId=bad/path", "/api/activity?runId=-dash"]) {
    const r = await drive(s.handler, { url, headers: auth });
    assert.equal(r.status, 400, `${url} → 400`);
    assert.deepEqual(jsonOf(r), { error: "bad_request" });
  }
});

test("QUERY /api/activity: bad categories/pageSize/order/afterSeq/cursor → 400", async () => {
  const s = makeServer();
  const auth = { authorization: "Bearer " + s.token };
  const base = "/api/activity?runId=run_x";
  const bad = [
    base + "&categories=bogus",
    base + "&categories=message,bogus",
    base + "&pageSize=0",
    base + "&pageSize=999",
    base + "&pageSize=abc",
    base + "&order=sideways",
    base + "&afterSeq=-1",
    base + "&afterSeq=1.5",
    base + "&cursor=!!!notbase64url",
  ];
  for (const url of bad) {
    const r = await drive(s.handler, { url, headers: auth });
    assert.equal(r.status, 400, `${url} → 400`);
    assert.deepEqual(jsonOf(r), { error: "bad_request" });
  }
});

test("QUERY: NO client-supplied runDir/workspaceRoot — rejected as unknown params", async () => {
  const s = makeServer();
  const auth = { authorization: "Bearer " + s.token };
  for (const url of [
    "/api/activity?runId=run_x&workspaceRoot=/evil",
    "/api/activity?runId=run_x&runDir=/evil",
    "/api/runs?limit=5&workspaceRoot=/evil",
    "/api/runs?host=0.0.0.0",
  ]) {
    const r = await drive(s.handler, { url, headers: auth });
    assert.equal(r.status, 400, `${url} → 400 (unknown param rejected)`);
    assert.deepEqual(jsonOf(r), { error: "bad_request" });
  }
});

test("QUERY /api/runs: invalid limit → 400", async () => {
  const s = makeServer();
  const auth = { authorization: "Bearer " + s.token };
  for (const url of ["/api/runs?limit=0", "/api/runs?limit=abc", "/api/runs?limit=-1", "/api/runs?limit=99999"]) {
    const r = await drive(s.handler, { url, headers: auth });
    assert.equal(r.status, 400);
    assert.deepEqual(jsonOf(r), { error: "bad_request" });
  }
});

// =====================================================================
// INJECTED ERRORS → fixed safe code, NO raw text, NO token
// =====================================================================
test("INJECTED service error → 500 internal, no raw text / token / path in body", async () => {
  const s = makeServer({
    activityFn: async () => { throw new Error("boom: /etc/secret/path " + "x"); },
    runsFn: async () => { throw new Error("runs-boom: " + s?.token + " leak"); },
  });
  const auth = { authorization: "Bearer " + s.token };
  const a = await drive(s.handler, { url: "/api/activity?runId=run_x", headers: auth });
  assert.equal(a.status, 500);
  assert.deepEqual(jsonOf(a), { error: "internal" });
  assert.ok(!a.body.includes("boom"), "no raw exception text");
  assert.ok(!a.body.includes("/etc/secret"), "no raw path");
  assert.ok(!a.body.includes(s.token), "no token in body");

  const r = await drive(s.handler, { url: "/api/runs", headers: auth });
  assert.equal(r.status, 500);
  assert.deepEqual(jsonOf(r), { error: "internal" });
  assert.ok(!r.body.includes("runs-boom"));
  assert.ok(!r.body.includes(s.token));
});

// =====================================================================
// HAPPY PATH — bounded client facts threaded to the read-only service
// =====================================================================
test("HAPPY /api/runs threads server-owned paths + client limit; never client paths", async () => {
  let captured = null;
  const s = makeServer({
    runsFn: async (input) => { captured = input; return { runs: [{ runId: "run_a" }], returnedCount: 1, matchedCount: 2, truncated: true }; },
  });
  const r = await drive(s.handler, { url: "/api/runs?limit=1", headers: { authorization: "Bearer " + s.token } });
  assert.equal(r.status, 200);
  assert.deepEqual(jsonOf(r), { runs: [{ runId: "run_a" }], returnedCount: 1, matchedCount: 2, truncated: true });
  // Server-owned paths are passed from the server config, NEVER from the query.
  assert.equal(captured.runDir, "/server/owned/runs");
  assert.equal(captured.workspaceRoot, "/server/owned/ws");
  assert.equal(captured.latest, 1);
});

test("HAPPY /api/activity threads runId/categories/pageSize/order; server-owned paths", async () => {
  let captured = null;
  const s = makeServer({
    activityFn: async (input) => {
      captured = input;
      return { runId: input.runId, available: true, unavailableReason: null, activity: { entries: [], total: 0 }, liveness: { ownerHeartbeat: "fresh", secondsSinceHeartbeat: 2 } };
    },
  });
  const r = await drive(s.handler, {
    url: "/api/activity?runId=run_y&categories=message,command&pageSize=10&order=desc",
    headers: { authorization: "Bearer " + s.token },
  });
  assert.equal(r.status, 200);
  assert.equal(captured.runId, "run_y");
  assert.deepEqual(captured.categories, ["message", "command"]);
  assert.equal(captured.pageSize, 10);
  assert.equal(captured.order, "desc");
  assert.equal(captured.runDir, "/server/owned/runs");
  assert.equal(captured.workspaceRoot, "/server/owned/ws");
  assert.equal(jsonOf(r).liveness.ownerHeartbeat, "fresh");
});

test("READ-ONLY: handler invokes only the read service and never mutates ctx (repeated reads)", async () => {
  let runsCalls = 0;
  let activityCalls = 0;
  const s = makeServer({
    runsFn: async () => { runsCalls += 1; return { runs: [], returnedCount: 0, matchedCount: 0, truncated: false }; },
    activityFn: async () => { activityCalls += 1; return { runId: "run_x", available: true, unavailableReason: null, activity: { entries: [] }, liveness: { ownerHeartbeat: "n/a", secondsSinceHeartbeat: null } }; },
  });
  const auth = { authorization: "Bearer " + s.token };
  for (let i = 0; i < 4; i += 1) {
    await drive(s.handler, { url: "/api/runs", headers: auth });
    await drive(s.handler, { url: "/api/activity?runId=run_x", headers: auth });
  }
  assert.equal(runsCalls, 4);
  assert.equal(activityCalls, 4);
  // The token the server issued at creation is stable across all reads (not rotated/leaked).
  assert.ok(typeof s.token === "string" && s.token.length >= 32);
});

// =====================================================================
// TOKEN never appears in ANY response body or header (sweep)
// =====================================================================
test("TOKEN: never present in any response body or header value across all outcomes", async () => {
  const s = makeServer();
  const auth = { authorization: "Bearer " + s.token };
  const cases = [
    { url: "/health" },
    { url: "/api/runs", headers: auth },
    { url: "/api/runs" }, // 401
    { url: "/api/activity?runId=run_x", headers: auth },
    { url: "/api/activity?runId=bad/x", headers: auth }, // 400
    { url: "/nope" }, // 404
    { method: "POST", url: "/api/runs", headers: auth }, // 405
  ];
  for (const c of cases) {
    const r = await drive(s.handler, c);
    assert.ok(!r.body.includes(s.token), `token absent from body (${c.method || "GET"} ${c.url})`);
    assert.ok(!JSON.stringify(r.headers).includes(s.token), `token absent from headers (${c.method || "GET"} ${c.url})`);
    assertSafeHeaders(r);
  }
});

// =====================================================================
// TOKEN CONTRACT — always exactly 64 lowercase hex derived from 32 bytes
// =====================================================================
test("TOKEN CONTRACT: issued token is exactly 64 lowercase hex derived from the injected 32-byte entropy", () => {
  // Entropy input contract: injected bytes deterministically produce the token.
  const ab = makeServer({ randomBytesFn: () => Buffer.alloc(32, 0xab) });
  assert.equal(ab.token, "ab".repeat(32), "deterministic bytes → hex");
  assert.equal(ab.token.length, 64);
  assert.match(ab.token, /^[0-9a-f]{64}$/);

  // Different injected bytes → different token.
  const cd = makeServer({ randomBytesFn: () => Buffer.alloc(32, 0xcd) });
  assert.equal(cd.token, "cd".repeat(32));
  assert.notEqual(ab.token, cd.token);

  // The generator receives the size argument (crypto.randomBytes shape): 32.
  let observedSize = null;
  makeServer({ randomBytesFn: (n) => { observedSize = n; return Buffer.alloc(n, 0x01); } });
  assert.equal(observedSize, 32);

  // Production default (no injection) → valid shape; two issuances differ.
  const d1 = makeServer();
  const d2 = makeServer();
  assert.match(d1.token, /^[0-9a-f]{64}$/);
  assert.match(d2.token, /^[0-9a-f]{64}$/);
  assert.notEqual(d1.token, d2.token, "default entropy is crypto-random, not constant");
});

test("TOKEN AUTHORITY: invalid randomBytesFn output rejected fail-closed before any side effect", () => {
  const bad = [
    () => Buffer.alloc(16),                  // too few bytes
    () => Buffer.alloc(64),                  // too many bytes
    () => Buffer.alloc(0),                   // zero bytes
    () => 12345,                             // not bytes (number)
    () => "not-bytes",                       // not bytes (string)
    () => null,                              // not bytes (null)
    () => { throw new Error("no entropy"); },// generator throws
  ];
  for (const fn of bad) {
    assert.throws(
      () => makeServer({ randomBytesFn: fn }),
      /invalid|random source|token/i,
      `rejects generator: ${fn.toString().slice(0, 48)}`,
    );
  }
});

test("TOKEN AUTHORITY: public arbitrary config.token is NOT accepted (always freshly issued)", () => {
  // The removed config.token knob must NOT pin the bearer; the factory always
  // issues a fresh 64-hex crypto-random token via randomBytes.
  const s = createOwnerDashboardServer({
    runDir: "/x", workspaceRoot: "/y",
    token: "fixed-injected-token-that-must-be-ignored",
  });
  assert.notEqual(s.token, "fixed-injected-token-that-must-be-ignored");
  assert.match(s.token, /^[0-9a-f]{64}$/);
});

// =====================================================================
// ENV AUTHORITY — provided env threaded; omitted env NOT threaded (→ process.env)
// =====================================================================
test("ENV AUTHORITY: provided env threaded to the service; omitted env is NOT threaded (falls through to process.env)", async () => {
  const stub = (input) => ({
    runId: input.runId, available: true, unavailableReason: null,
    activity: { entries: [] }, liveness: { ownerHeartbeat: "n/a", secondsSinceHeartbeat: null },
  });

  // Provided env → threaded verbatim to the service.
  let captured = null;
  let s = createOwnerDashboardServer({
    runDir: "/x", workspaceRoot: "/y", env: { LEAK_TOKEN: "abc" },
    getOwnerActivityFn: async (input) => { captured = input; return stub(input); },
  });
  await drive(s.handler, { url: "/api/activity?runId=run_x", headers: { authorization: "Bearer " + s.token } });
  assert.deepEqual(captured.env, { LEAK_TOKEN: "abc" }, "provided env threaded");

  // Omitted env → key ABSENT from the service input, so the service+projector
  // SSOT default (createSecretRedactor(env ?? process.env)) applies in production.
  captured = null;
  s = createOwnerDashboardServer({
    runDir: "/x", workspaceRoot: "/y",
    getOwnerActivityFn: async (input) => { captured = input; return stub(input); },
  });
  await drive(s.handler, { url: "/api/activity?runId=run_x", headers: { authorization: "Bearer " + s.token } });
  assert.ok(!("env" in captured), "omitted env is not threaded (falls through to process.env)");
});

// =====================================================================
// ARCHITECTURE — only node:http/crypto/url + the service; no SDK/zod/commands
// =====================================================================
test("ownerDashboardServer.js uses only node:http/crypto/url + the service (no SDK/zod/commands)", async () => {
  const { readFileSync: rf } = await import("node:fs");
  const { fileURLToPath } = await import("node:url");
  const src = rf(join(fileURLToPath(new URL(".", import.meta.url)), "..", "src", "ownerDashboardServer.js"), "utf8");
  assert.ok(src.includes('from "node:http"'), "uses node:http");
  assert.ok(src.includes('from "node:crypto"'), "uses node:crypto");
  assert.ok(src.includes('from "node:url"'), "uses node:url");
  assert.ok(src.includes("ownerDashboard"), "uses the composition service");
  assert.ok(!src.includes("@modelcontextprotocol/sdk"), "no SDK");
  assert.ok(!src.includes('from "zod"'), "no zod");
  assert.ok(!src.includes('from "./commands/'), "no commands/");
});
