#!/usr/bin/env node
// scripts/gen-surface.mjs
//
// P4-乙 Phase 1a — the generative reference layer for WAO's two agent-facing
// surfaces (MCP tools + CLI help). Zero new third-party dependencies: it uses
// the existing production deps only (@modelcontextprotocol/sdk InMemoryTransport
// for the MCP face) plus node builtins.
//
// What it does:
//   - MCP face (behavior-derived, not hand-maintained): constructs a REAL
//     createWaoMcpServer against a throwaway registry/runDir under os.tmpdir()
//     (explicit absolute path, cleaned up after), connects an SDK Client over an
//     InMemoryTransport pair, and renders docs/surface/mcp-tools.md from the
//     live tools/list result. listTools never invokes a handler, so there is no
//     provider connection, no token, and no spawn — construction-time only.
//   - CLI face: imports HELP_TEXT from src/cliHelp.js (the same SSOT the CLI
//     prints) and embeds it verbatim in docs/surface/cli.md.
//
// Determinism contract (guarded by test/isolation-infra/docsSurface.test.js):
//   - output is joined with "\n" only (never os.EOL), contains no timestamps,
//     no temp paths, no random values — same input ⇒ byte-identical output;
//   - tool order is the exact tools/list (registration) order;
//   - .gitattributes pins docs/surface/*.md to eol=lf so checkouts stay stable.
//
// Usage: npm run gen:surface   (writes both files; import { generate } for the
// in-memory strings — importing never writes).

import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { HELP_TEXT } from "../src/cliHelp.js";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const MCP_TOOLS_MD = "docs/surface/mcp-tools.md";
const CLI_MD = "docs/surface/cli.md";

const MARKER = "<!-- GENERATED by scripts/gen-surface.mjs — DO NOT EDIT; run npm run gen:surface -->";
const AUDIENCE = "Audience: repository-level agents and humans; the online Lead reads SKILL.md + per-result semanticNotes instead.";

// =====================================================================
// MCP face rendering
// =====================================================================

/**
 * Resolve a one-level `$ref` against the schema DOCUMENT root. The MCP SDK's
 * zod→JSON conversion references repeated zod instances via root-relative JSON
 * Pointers (e.g. "#/properties/baseCommit/anyOf/0"), not $defs — so deref walks
 * the pointer from the document root. `depth` bounds the hop chain (cycle
 * guard); an unresolvable ref is returned as-is so the summary stays truthful.
 */
function deref(schema, rootDoc, depth = 0) {
  if (depth > 8) return schema;
  if (!schema || typeof schema !== "object" || typeof schema.$ref !== "string") return schema;
  const pointer = schema.$ref;
  if (!pointer.startsWith("#/") || pointer.includes("//")) return schema;
  let node = rootDoc;
  for (const rawSegment of pointer.slice(2).split("/")) {
    const segment = rawSegment.replace(/~1/g, "/").replace(/~0/g, "~");
    if (node == null || typeof node !== "object" || !(segment in node)) return schema;
    node = node[segment];
  }
  if (node == null || typeof node !== "object") return schema;
  return deref(node, rootDoc, depth + 1);
}

/**
 * Summarize a JSON-schema subschema into a compact type label for the reference
 * table (top-level fields only — never a full schema copy).
 */
function summarizeType(schema, rootDoc) {
  const s = deref(schema, rootDoc);
  if (!s || typeof s !== "object") return "any";
  if (Array.isArray(s.anyOf)) {
    const members = s.anyOf.map((m) => summarizeType(m, rootDoc));
    return [...new Set(members)].join("|");
  }
  if (Array.isArray(s.oneOf)) {
    const members = s.oneOf.map((m) => summarizeType(m, rootDoc));
    return [...new Set(members)].join("|");
  }
  if (Array.isArray(s.type)) return [...new Set(s.type)].join("|");
  switch (s.type) {
    case "array":
      return `array<${summarizeType(s.items, rootDoc)}>`;
    case "object":
      return "object";
    case "string":
    case "integer":
    case "number":
    case "boolean":
    case "null":
      return s.type;
    default:
      return s.type ?? "any";
  }
}

/**
 * Closed-set values (enum members / const literals) for the notes column,
 * collected across anyOf/oneOf branches except pure-null branches. Patterns,
 * bounds, and defaults are deliberately omitted (rendering discipline).
 */
function closedSetValues(schema, rootDoc) {
  const s = deref(schema, rootDoc);
  if (!s || typeof s !== "object") return [];
  if (Array.isArray(s.anyOf) || Array.isArray(s.oneOf)) {
    const branches = s.anyOf ?? s.oneOf;
    const values = [];
    for (const branch of branches) values.push(...closedSetValues(branch, rootDoc));
    return values;
  }
  if (Array.isArray(s.enum)) return s.enum.map((v) => String(v));
  if ("const" in s) return [String(s.const)];
  // A scalar ARRAY whose items are an enum/const carries that closed set as its
  // domain — surface it (object properties are NOT descended: top-level only).
  if (s.type === "array" && s.items && typeof s.items === "object") {
    return closedSetValues(s.items, rootDoc);
  }
  return [];
}

function fieldNotes(schema, rootDoc) {
  const s = deref(schema, rootDoc);
  const parts = [];
  if (typeof s.description === "string" && s.description.length > 0) parts.push(s.description);
  const values = closedSetValues(s, rootDoc);
  if (values.length > 0) {
    // "const" only for a DIRECT single-literal schema (z.literal → {const});
    // unions (e.g. nullable enums) and enum arrays are closed SETS → "enum".
    const isDirectConst = "const" in s
      && !Array.isArray(s.enum) && !Array.isArray(s.anyOf) && !Array.isArray(s.oneOf);
    const label = isDirectConst ? "const" : "enum";
    parts.push(`${label}: ${values.join(" | ")}`);
  }
  return parts.join(" — ");
}

/** Escape a value for a markdown table cell (pipes + line breaks). */
function mdCell(value) {
  return String(value).replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}

/**
 * Render the TOP-LEVEL field table of an input/output schema: name/type/
 * required + description & closed-set enum values. Nested shapes are NOT
 * expanded (the wire is the authority) — this keeps every tool section small.
 */
function fieldTableLines(schema) {
  const props = schema && typeof schema === "object" && schema.properties
    && typeof schema.properties === "object" ? schema.properties : null;
  if (!props || Object.keys(props).length === 0) {
    return ["*(no top-level fields)*"];
  }
  const rootDoc = schema;
  const required = new Set(Array.isArray(schema.required) ? schema.required : []);
  const lines = [
    "| name | type | required | notes |",
    "| --- | --- | --- | --- |",
  ];
  for (const [name, sub] of Object.entries(props)) {
    lines.push(`| ${mdCell(name)} | ${mdCell(summarizeType(sub, rootDoc))} | ${required.has(name) ? "yes" : "no"} | ${mdCell(fieldNotes(sub, rootDoc))} |`);
  }
  return lines;
}

function formatHint(value) {
  return value === undefined ? "unset" : String(value);
}

function pushToolSection(lines, tool) {
  lines.push(`## ${tool.name}`);
  lines.push("");
  lines.push(tool.description ?? "");
  lines.push("");
  const a = tool.annotations ?? {};
  lines.push(
    `Annotations: readOnlyHint=${formatHint(a.readOnlyHint)}, `
    + `destructiveHint=${formatHint(a.destructiveHint)}, `
    + `idempotentHint=${formatHint(a.idempotentHint)}, `
    + `openWorldHint=${formatHint(a.openWorldHint)}`,
  );
  lines.push("");
  lines.push("Input:");
  lines.push("");
  lines.push(...fieldTableLines(tool.inputSchema));
  lines.push("");
  lines.push("Output:");
  lines.push("");
  lines.push(...fieldTableLines(tool.outputSchema));
  lines.push("");
}

function renderMcpToolsMd(tools) {
  const lines = [
    MARKER,
    `# WAO MCP tool surface (${tools.length} tools)`,
    "",
    AUDIENCE,
    "",
    "Rendered from the live `tools/list` of a real `createWaoMcpServer` over an SDK "
    + "InMemoryTransport pair (throwaway registry/runDir under os.tmpdir(); no provider "
    + "connection, no tokens, no spawn — listTools never invokes a handler). Sections are "
    + "in the exact registration order. Each section carries the description verbatim, the "
    + "four annotation hints, and the TOP-LEVEL input/output schema fields (name/type/required "
    + "+ enum closed sets; const is a one-value closed set). Nested object/array shapes, "
    + "patterns, bounds, and defaults are omitted — the authoritative contract is the wire "
    + "itself (src/mcp/server.js + src/mcp/toolSurface.js).",
    "",
  ];
  for (const tool of tools) pushToolSection(lines, tool);
  return lines.join("\n") + "\n";
}

// =====================================================================
// CLI face rendering
// =====================================================================

function renderCliMd() {
  const head = [
    MARKER,
    "# WAO CLI help",
    "",
    AUDIENCE,
    "",
    "Verbatim `wao help` output (`HELP_TEXT` in `src/cliHelp.js` — the same SSOT the CLI "
    + "itself prints; see also docs/surface/mcp-tools.md for the MCP face).",
    "",
    "",
  ].join("\n");
  // HELP_TEXT ends with "\n", so the closing fence lands directly on the next line.
  return head + "```text\n" + HELP_TEXT + "```\n";
}

// =====================================================================
// generate()
// =====================================================================

/**
 * Derive both surface reference documents. Pure with respect to the working
 * tree: everything throwaway lives under os.tmpdir() (explicit absolute path)
 * and is removed before returning. Byte-deterministic for identical inputs.
 *
 * @returns {Promise<{ "docs/surface/mcp-tools.md": string, "docs/surface/cli.md": string }>}
 */
export async function generate() {
  const dir = mkdtempSync(join(tmpdir(), "wao-gen-surface-"));
  let client;
  let server;
  try {
    const registryPath = join(dir, "agents.json");
    writeFileSync(
      registryPath,
      JSON.stringify({ agents: { coder_low: { backend: "claude-code", cwd: dir } } }),
      "utf8",
    );
    const { createWaoMcpServer } = await import("../src/mcp/server.js");
    const { Client } = await import("@modelcontextprotocol/sdk/client");
    const { InMemoryTransport } = await import("@modelcontextprotocol/sdk/inMemory.js");
    server = createWaoMcpServer({ registryPath, runDir: join(dir, "runs") });
    client = new Client({ name: "wao-gen-surface", version: "0.0.1" }, { capabilities: {} });
    const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
    await Promise.all([server.connect(serverTransport), client.connect(clientTransport)]);
    const tools = (await client.listTools()).tools;
    return {
      [MCP_TOOLS_MD]: renderMcpToolsMd(tools),
      [CLI_MD]: renderCliMd(),
    };
  } finally {
    if (client) await client.close().catch(() => {});
    if (server) await server.close().catch(() => {});
    rmSync(dir, { recursive: true, force: true });
  }
}

// Write the files only when run as the main module (never on import).
if (import.meta.main) {
  const files = await generate();
  for (const [rel, content] of Object.entries(files)) {
    const target = join(REPO_ROOT, rel);
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, content, "utf8");
    console.log(`[gen-surface] wrote ${rel} (${Buffer.byteLength(content, "utf8")} bytes)`);
  }
}
