// test/isolation-infra/docsSurface.test.js
//
// P4-乙 Phase 1a — generative reference layer guard (docs/surface/).
//
// docs/surface/mcp-tools.md + docs/surface/cli.md are GENERATED by
// scripts/gen-surface.mjs: the MCP face is derived from the live tools/list of
// a real createWaoMcpServer over an SDK InMemoryTransport pair (throwaway
// registry/runDir under os.tmpdir(); no provider connection, no token, no
// spawn — listTools never invokes a handler), and the CLI face is HELP_TEXT
// from src/cliHelp.js embedded verbatim.
//
// This test pins the COMMITTED files to the generator: read disk → normalize
// \r\n → \n → assert.equal against the fresh generate() output. Discipline: the
// test does NOT re-implement any formatting logic — the generator under test IS
// the formatter. The structural spot-checks use only facts already exported by
// repo SSOTs (toolSurface.js TOOLS, cliHelp.js HELP_TEXT), not re-derived
// rendering.
//
// Pure-group safe: in-memory transports only, temp fixtures under os.tmpdir()
// with explicit absolute paths, zero subprocess spawn, zero git, zero network.

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

import { generate } from "../../scripts/gen-surface.mjs";
import { HELP_TEXT } from "../../src/cliHelp.js";
import { TOOLS } from "../../src/mcp/toolSurface.js";

const REPO_ROOT = resolve(import.meta.dirname, "../..");
const MCP_TOOLS_MD = "docs/surface/mcp-tools.md";
const CLI_MD = "docs/surface/cli.md";
const MARKER = "GENERATED by scripts/gen-surface.mjs";

/** Read a repo file and normalize CRLF → LF (checkout line-ending independence). */
async function readNormalized(rel) {
  return (await readFile(resolve(REPO_ROOT, rel), "utf8")).replace(/\r\n/g, "\n");
}

test("docsSurface-1: committed docs/surface files equal generate() output byte-for-byte", async () => {
  const generated = await generate();
  for (const rel of [MCP_TOOLS_MD, CLI_MD]) {
    const onDisk = await readNormalized(rel);
    assert.equal(
      onDisk,
      generated[rel],
      `${rel} is stale — run npm run gen:surface and commit the output`,
    );
  }
});

test("docsSurface-2: both files carry the GENERATED marker", async () => {
  for (const rel of [MCP_TOOLS_MD, CLI_MD]) {
    const onDisk = await readNormalized(rel);
    assert.ok(onDisk.includes(MARKER), `${rel} contains the GENERATED marker`);
    assert.ok(onDisk.startsWith("<!--"), `${rel} starts with the marker comment`);
  }
});

test("docsSurface-3: mcp-tools.md has one section per frozen tool, in registration order", async () => {
  const onDisk = await readNormalized(MCP_TOOLS_MD);
  const headings = [...onDisk.matchAll(/^## ([a-z0-9_]+)$/gm)].map((m) => m[1]);
  assert.deepEqual(
    headings,
    TOOLS,
    "per-tool section headings equal the frozen toolSurface.js SSOT (set + order)",
  );
});

test("docsSurface-4: HELP_TEXT is a non-empty long string; cli.md embeds it verbatim", async () => {
  assert.equal(typeof HELP_TEXT, "string", "HELP_TEXT is a string");
  assert.ok(HELP_TEXT.length > 1000, `HELP_TEXT is long (got ${HELP_TEXT.length} chars)`);
  assert.ok(HELP_TEXT.includes("Commands:"), "HELP_TEXT contains the Commands section");
  assert.ok(HELP_TEXT.endsWith("\n"), "HELP_TEXT ends with a newline");
  const onDisk = await readNormalized(CLI_MD);
  assert.ok(
    onDisk.includes("```text\n" + HELP_TEXT + "```"),
    "cli.md embeds HELP_TEXT verbatim inside the fenced code block",
  );
});
